# Generated by Django 3.0.5 on 2021-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
